const expectedShapes = [
    'rArrow',
    'lArrow',
    'uArrow',
    'dArrow',
    'ruArrow',
    'ldArrow',
    'rdArrow',
    'luArrow',
    'hLine',
    'vLine',
    'square',
    'circle',
    'diamond',
    'triangle',
    'cylinder',
    'file',
    'user',
    'cloud',
    'cwTopArrow',
    'ccwTopArrow',
    'cwBotArrow',
    'ccwBotArrow',
    'cwsqTopArrow'
];
export default expectedShapes;